version: '3.3'

services:
  puppeteer:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ".:/code"
    entrypoint: ["sh", "-c", "sleep infinity"]
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
      - LC_ALL=en_US.UTF-8
