version: '3.3'

services:
  docker-puppeteer:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ".:/code"
    entrypoint: ["sh", "-c", "sleep infinity"]