version: 2.1

# parameters only | params only
parameters:
  feature-domain:
    type: string
    default: ""

  tool:
    type: string
    default: "puppeteer"

  browser:
    type: string
    default: "chrome"

  env:
    type: string
    default: "dev"

  test_suite_name:
    type: string
    default: ""

  trigger_api:
    default: true
    type: boolean

  trigger_cli:
    default: true
    type: boolean

  trigger_implementation:
    default: true
    type: boolean

  trigger_linux:
    default: true
    type: boolean

  os:
    type: string
    default: "linux"

orbs:
  win: circleci/windows@2.4.0
  macos: circleci/macos@2.3.4
  slack: circleci/slack@4.9.3
  browser-tools: circleci/browser-tools@1.4.1

working_directory: ~/code

# job build only
jobs:
  build-latest:
    environment:
      - ENV=<< pipeline.parameters.env >>
      - FEATURE_DOMAIN=<< pipeline.parameters.feature-domain >>
      - TEST_SUITE_NAME=<< pipeline.parameters.test_suite_name >>
    working_directory: /home/pptruser/code
    docker:
      - image: lecaoquochung/puppeteer:latest
        environment:
          TZ: "Asia/Tokyo"
    steps:
      - checkout
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            ./.circleci/env/var.sh
      - restore_cache:
          keys:
          - v1-build-yarn-{{ checksum "package.json" }}
      - run:
          name: Submodule
          command: |
            ./.circleci/submodule.sh
      - run: 
          name: Build Dependencies
          command: |
            ./.circleci/job/shared/build-dependencies.sh
      - run:
          name: DOMAIN INFO
          command: |
            ./.circleci/job/shared/server-domain-info.sh
      - run:
          name: TEST SCOPE
          command: |
            ./.circleci/job/shared/scope.sh
      - save_cache:
          key: v1-build-yarn-{{ checksum "package.json" }}
          paths:
            - "/home/pptruser/code/node_modules"

  build-version:
    environment:
      - ENV=<< pipeline.parameters.env >>
      - FEATURE_DOMAIN=<< pipeline.parameters.feature-domain >>
      - TEST_SUITE_NAME=<< pipeline.parameters.test_suite_name >>
    working_directory: /home/pptruser/code
    docker:
      - image: lecaoquochung/puppeteer:node-18.17.0
        environment:
          TZ: "Asia/Tokyo"
    steps:
      - checkout
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            ./.circleci/env/var.sh
      - restore_cache:
          keys:
          - v1-build-yarn-{{ checksum "package.json" }}
      - run:
          name: Submodule
          command: |
            ./.circleci/submodule.sh
      - run: 
          name: Build Dependencies
          command: |
            ./.circleci/job/shared/build-dependencies.sh
      - run:
          name: DOMAIN INFO
          command: |
            ./.circleci/job/shared/server-domain-info.sh
      - run:
          name: TEST SCOPE
          command: |
            ./.circleci/job/shared/scope.sh
      - save_cache:
          key: v1-build-yarn-{{ checksum "package.json" }}
          paths:
            - "/home/pptruser/code/node_modules"